version: '3'
services:
  bookdbserver:
    image: mysql:8.0.30
    container_name: booksdbserver
    environment:
      - MYSQL_ROOT_PASSWORD=mysq1DbP@ss
      - MYSQL_DATABASE=mra.booksdb
    ports:
      - 5210:3306
  roomdbserver:
    image: mysql:8.0.30
    container_name: roomsdbserver
    environment:
      - MYSQL_ROOT_PASSWORD=mysq1DbP@ss
      - MYSQL_DATABASE=mra.roomsdb
    ports:
      - 5310:3306
  identitydbserver:
    image: mysql:8.0.30
    container_name: identitydbserver
    environment:
      - MYSQL_ROOT_PASSWORD=mysq1DbP@ss
      - MYSQL_DATABASE=mra.identitydb
    ports:
      - 5010:3306
  gateway:
    image: "dkrishen/mragateway:v3"
    container_name: gateway
    ports:
      - 5100:80
  identity:
    image: "dkrishen/mraidentity:v3"
    container_name: identity
    ports:
      - 5000:80
    depends_on:
      - identitydbserver
  book:
    image: "dkrishen/mrabooks:v3"
    container_name: books
    ports:
      - 5200:80
    depends_on:
      - bookdbserver
  room:
    image: "dkrishen/mrarooms:v3"
    container_name: rooms
    ports:
      - 5300:80
    depends_on:
        - roomdbserver
  user:
    image: "dkrishen/mrausers:v3"
    container_name: users
    ports:
      - 5020:80
    depends_on:
      - identitydbserver