version: '3'
services:
  bookdbserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: booksdbserver
    environment:
      SA_PASSWORD: "mssq1DbP@ss"
      ACCEPT_EULA: "Y"
    ports:
      - 5210:1433
  roomdbserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: roomsdbserver
    environment:
      SA_PASSWORD: "mssq1DbP@ss"
      ACCEPT_EULA: "Y"
    ports:
      - 5310:1433
  identitydbserver:
    image: "mcr.microsoft.com/mssql/server"
    container_name: identitydbserver
    environment:
      SA_PASSWORD: "mssq1DbP@ss"
      ACCEPT_EULA: "Y"
    ports:
      - 5010:1433
  gateway:
    image: "dkrishen/mragateway:v2"
    container_name: gateway
    ports:
      - 5100:80
  identity:
    image: "dkrishen/mraidentity:v2"
    container_name: identity
    ports:
      - 5000:80
    depends_on:
      - identitydbserver
  book:
    image: "dkrishen/mrabooks:v2"
    container_name: books
    ports:
      - 5200:80
    depends_on:
      - bookdbserver
  room:
    image: "dkrishen/mrarooms:v2"
    container_name: rooms
    ports:
      - 5300:80
    depends_on:
        - roomdbserver
  user:
    image: "dkrishen/mrausers:v2"
    container_name: users
    ports:
      - 5020:80
    depends_on:
      - identitydbserver
  # angular:
  #   image: "dkrishen/mraangular:v1"
  #   container_name: angular
  #   ports:
  #     - 4200:80