version: '3'

services:
  bookdbserver:
    # image: arm64v8/mysql:8.0.30
    image: mysql:8.0.30
    container_name: booksdbserver
    command: 
      --innodb_buffer_pool_size=5M 
      --innodb_log_buffer_size=256K
      --max_connections=10 
      --key_buffer_size=8 
      --thread_cache_size=0 
      --host_cache_size=0 
      --innodb_ft_cache_size=1600000 
      --innodb_ft_total_cache_size=32000000 
      --thread_stack=131072 
      --sort_buffer_size=32K 
      --read_buffer_size=8200 
      --read_rnd_buffer_size=8200 
      --max_heap_table_size=16K 
      --tmp_table_size=1K 
      --bulk_insert_buffer_size=0 
      --join_buffer_size=128 
      --net_buffer_length=1K 
      --innodb_sort_buffer_size=64K 
      --binlog_cache_size=4K 
      --binlog_stmt_cache_size=4K 
      --performance_schema=off
    environment:
      - MYSQL_ROOT_PASSWORD=mysq1DbP@ss
      - MYSQL_DATABASE=mra.booksdb
    ports:
      - 5210:3306
    volumes:
      - /mra/bookdb:/var/lib/mysql

  roomdbserver:
    # image: arm64v8/mysql:8.0.30
    image: mysql:8.0.30
    container_name: roomsdbserver
    command: 
      --innodb_buffer_pool_size=5M 
      --innodb_log_buffer_size=256K
      --max_connections=10 
      --key_buffer_size=8 
      --thread_cache_size=0 
      --host_cache_size=0 
      --innodb_ft_cache_size=1600000 
      --innodb_ft_total_cache_size=32000000 
      --thread_stack=131072 
      --sort_buffer_size=32K 
      --read_buffer_size=8200 
      --read_rnd_buffer_size=8200 
      --max_heap_table_size=16K 
      --tmp_table_size=1K 
      --bulk_insert_buffer_size=0 
      --join_buffer_size=128 
      --net_buffer_length=1K 
      --innodb_sort_buffer_size=64K 
      --binlog_cache_size=4K 
      --binlog_stmt_cache_size=4K 
      --performance_schema=off
    environment:
      - MYSQL_ROOT_PASSWORD=mysq1DbP@ss
      - MYSQL_DATABASE=mra.roomsdb
    ports:
      - 5310:3306
    volumes:
      - /mra/roomdb:/var/lib/mysql

  identitydbserver:
    # image: arm64v8/mysql:8.0.30
    image: mysql:8.0.30
    container_name: identitydbserver
    command: 
      --innodb_buffer_pool_size=5M 
      --innodb_log_buffer_size=256K
      --max_connections=10 
      --key_buffer_size=8 
      --thread_cache_size=0 
      --host_cache_size=0 
      --innodb_ft_cache_size=1600000 
      --innodb_ft_total_cache_size=32000000 
      --thread_stack=131072 
      --sort_buffer_size=32K 
      --read_buffer_size=8200 
      --read_rnd_buffer_size=8200 
      --max_heap_table_size=16K 
      --tmp_table_size=1K 
      --bulk_insert_buffer_size=0 
      --join_buffer_size=128 
      --net_buffer_length=1K 
      --innodb_sort_buffer_size=64K 
      --binlog_cache_size=4K 
      --binlog_stmt_cache_size=4K 
      --performance_schema=off
    environment:
      - MYSQL_ROOT_PASSWORD=mysq1DbP@ss
      - MYSQL_DATABASE=mra.identitydb
    ports:
      - 5010:3306
    volumes:
      - /mra/identitydb:/var/lib/mysql

  gateway:
    image: "dkrishen/mragateway:host-0.1"
    container_name: gateway
    ports:
      - 5100:80

  identity:
    image: "dkrishen/mraidentity:host-0.1"
    container_name: identity
    ports:
      - 5000:80
    depends_on:
      - identitydbserver

  booking:
    image: "dkrishen/mrabookings:host-0.1"
    container_name: bookings
    ports:
      - 5200:80
    depends_on:
      - bookdbserver
      
  room:
    image: "dkrishen/mrarooms:host-0.1"
    container_name: rooms
    ports:
      - 5300:80
    depends_on:
        - roomdbserver

  user:
    image: "dkrishen/mrausers:host-0.1"
    container_name: users
    ports:
      - 5020:80
    depends_on:
      - identitydbserver

  angular.spa:
    image: "dkrishen/mraspa:host-0.1"
    container_name: spa
    ports:
      - 4200:80